name: "Hydrate AWS Portfolio"

on:
  push:
    branches: [ main ]
    paths:
      - 'projects/**'
      - 'infrastructure/**'
  workflow_dispatch: # Allows manual trigger from GH UI

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: projects/01-secure-rag
          framework: terraform
          soft_fail: true 
          quiet: true # Only show failures

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --soft-fail
          working_directory: projects/01-secure-rag
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Terraform State
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: hydrate-infra.yml
          name: terraform-state
          if_no_artifact_found: warn
          path: projects/01-secure-rag/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # This line will now be ignored if the secret is empty/deleted
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Python for Lambda Layers
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build Lambda Layer
        run: |
          cd projects/01-secure-rag
          rm -rf layer_build
          mkdir -p layer_build/python
          pip install -r requirements-faiss.txt -t layer_build/python/ --platform manylinux2014_x86_64 --implementation cp --python-version 3.12 --only-binary=:all: --upgrade

      - name: Install Build Dependencies
        run: pip install --upgrade pip

      - name: Terraform Init & Apply
        run: |
          cd projects/01-secure-rag
          terraform init
          terraform apply -auto-approve

      - name: Upload Terraform State
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: projects/01-secure-rag/terraform.tfstate